# This file was generated by GoReleaser. DO NOT EDIT.
cask "hangar" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "028054adaffd431ebb23276051a11864ae1e237e311f304d8c232873ab692e9e"
      url "https://github.com/louisescher/hangar/releases/download/v#{version}/hangar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e48a7f4455287645d9a8d2e91419dc5c4318f5efd5d06b2d37db08fee61fae97"
      url "https://github.com/louisescher/hangar/releases/download/v#{version}/hangar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63929000303f15f075a40935079ccf8bf56d260e932d7c8559cf2c81a71a3c95"
      url "https://github.com/louisescher/hangar/releases/download/v#{version}/hangar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5287f33d42c31881ce82d558bda7d114a615ded5756e7983a35ae2793bfab9ba"
      url "https://github.com/louisescher/hangar/releases/download/v#{version}/hangar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hangar"
  desc "A TUI package manager for AI agent skills"
  homepage "https://github.com/louisescher/hangar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hangar"

  # No zap stanza required

end
